server:
  port: 8201
# 服务名
spring:
  application:
    name: service-hosp

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    #设置sentinel地址
    sentinel:
      transport:
        dashboard: dashboard=http://127.0.0.1:8858

  #mongodb
  data:
    mongodb:
      host: 192.168.44.163
      port: 27017
      database: registration

  #rabbitmq地址
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  #配置mapper xml文件的路径
  #mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
mybatis-plus:
  mapper-locations: classpath:com/xmj/regis_hosp/mapper/xml/*.xml

  #开启sentinel
feign:
  sentinel:
    enabled: true